#Series
Array uni-dimensional com dados e rótulos de um eixo

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/Laisgraca/Pandas/refs/heads/main/gasprices.csv', sep='\t')

In [4]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [5]:
data['ESTADO'] # Selecionando uma coluna inteira

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [6]:
# Outra forma de selecionar a coluna inteira
# Só funciona para colunas com nomes sem espaço,acentos e etc)

data.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [8]:
type(data['ESTADO']) # Informa o tipo de dados

pandas.core.series.Series

In [9]:
data.iloc[4] # Selecionando as informações contidas no índice [4] do dataframe

DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                   NORDESTE
ESTADO                                    ALAGOAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  103
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.181
DESVIO PADRÃO REVENDA                       0.078
PREÇO MÍNIMO REVENDA                         1.05
PREÇO MÁXIMO REVENDA                          1.4
MARGEM MÉDIA REVENDA                         0.24
COEF DE VARIAÇÃO REVENDA                    0.066
PREÇO MÉDIO DISTRIBUIÇÃO                    0.941
DESVIO PADRÃO DISTRIBUIÇÃO                  0.077
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.7441
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.0317
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.082
Name: 4, dtype: object

In [11]:
type(data.iloc[4])

pandas.core.series.Series

# Criando uma Series

In [12]:
pd.Series([6.0,9.5,8.5])

0    6.0
1    9.5
2    8.5
dtype: float64

# Alterando o nome do índice e da Series

In [13]:
pd.Series([6.0,9.5,8.5], index=['Prova 1','Prova 2','Prova 3'], name = 'Notas do Aluno Andrew')

Prova 1    6.0
prova 2    9.5
prova 3    8.5
Name: Notas do Aluno Andrew, dtype: float64